[package]
name = "project"
version = "0.1.0"
edition = "2021"
rprompt = "1.0.5"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rprompt = "1.0.5"